@baseUrl = http://localhost:3333
@token = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Caio Sendin",
    "email": "caio@acme.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
    "email": "caio@acme.com",
    "password": "123456"
}

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}
