@baseUrl = http://localhost:3333
@token = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Lucas Diniz",
    "email": "lucasdiniz@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
    "email": "lucasdiniz@gmail.com",
    "password": "123456"
}

###

# @name authenticate_with_github
POST {{baseUrl}}/sessions/github
Content-Type: application/json

{
    "code": "385da2d63d4b0542ccd0"
}

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name request_password_recover
POST {{baseUrl}}/password/recover
Content-Type: application/json

{
    "email": "caio@acme.com"
}

###

# @name reset_password
POST {{baseUrl}}/password/reset
Content-Type: application/json

{
    "code": "10f6b166-4624-45cf-a33f-7a94fa818d78",
    "password": "000000"
}

###

# @name create_organization
POST {{baseUrl}}/organizations
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Ascombet",
    "domain": "ascombet.com.br",
    "attachUsersByDomain": true
}

###

# @name get_membership
GET {{baseUrl}}/organization/ascombet/membership
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_organization
GET {{baseUrl}}/organizations/ascombet
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_organizations
GET {{baseUrl}}/organizations
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name shutdown_organizations
DELETE {{baseUrl}}/organizations/ascombet
Content-Type: application/json
Authorization: Bearer {{token}}
